name: Deploy ROC to gh-pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: main        # change if your HTML lives on a different branch
          fetch-depth: 0   # need full history to detect gh-pages

      - name: Configure Git
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Switch to (or create) gh-pages
        run: |
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git rm -rf .
          fi

      - name: Copy and rename ROC comparison
        run: |
          cp results/roc_comparison.html index.html

      - name: Commit & push
        run: |
          git add index.html
          git commit -m "Deploy updated ROC comparison" || echo "No changes to commit"
          git push origin gh-pages --force
